#!/bin/bash 

STORAGE="/cygdrive/e/Educational dump/udemy-rips"
ANKISTORAGE="/cygdrive/e/AnkiMedia/User 1/collection.media"
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")


cd "$STORAGE"
select COURSE in $(find "$STORAGE" -type d -and ! -iname "ankicsv" -and ! -iname "udemy-rips" -printf "%f\n") "Exit Script";
do
CSVNAME="$ANKISTORAGE/ankicsv/$COURSE.csv"
  case $COURSE in
      "Exit Script")
          echo "Script exiting gracefully.";break
          ;;
       *)
         if [[ -f "$CSVNAME" && -s "$CSVNAME" ]]; then
		echo "$CSVNAME already exists and has content.  Terminating program."; less "$CSVNAME"; exit 1
	 else 
		touch "$CSVNAME"
		cd "$COURSE"
#tee hee titname
		for each in $(find -type f -printf "%f\n"); do titname=$(echo "$each" | awk -F "=" '{print $2}'); echo "$titname;[sound:$each]" >> "$CSVNAME"; cp -v "$each" "$ANKISTORAGE/$each"; done
		sort "$CSVNAME" > tempcsv; mv tempcsv "$CSVNAME"
	 fi
          ;;
  esac
done


IFS=$SAVEIFS
