#!/bin/bash 

STORAGE="/cygdrive/e/Educational dump/udemy-rips"
ANKISTORAGE="/cygdrive/e/AnkiMedia/User 1/collection.media"
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
VISUAL=${VISUAL:-"vim"}


mediamenu(){
cd "$STORAGE"
echo "Type \"list\" or \"quit\" to do either at any time."
select COURSE in $(find "$STORAGE" -type d -and ! -iname "ankicsv" -and ! -iname "udemy-rips" -printf "%f\n" | sort) "Exit Script";
do
CSVNAME="$ANKISTORAGE/ankicsv/$COURSE.csv"
  case $COURSE in
      "Exit Script")
          echo "Script exiting gracefully."; exit 0
          ;;
       *)
	 if [[ $REPLY == "list" ]] ; then
		clear; mediamenu
	 elif [[ $REPLY == "quit" ]] ; then
          	echo "Script exiting gracefully."; exit 0
         elif [[ -f "$CSVNAME" && -s "$CSVNAME" ]]; then
		echo -e "\n"; read -p "$CSVNAME already exists and has content. Press enter to review changes in editor."; $VISUAL "$CSVNAME"
		clear; mediamenu
	 else 
		touch $CSVNAME
		mkdir $ANKISTORAGE/$COURSE; 
		cd "$COURSE"
#tee hee titname
		for each in $(find -type f -printf "%f\n"); do titname=$(echo "$each" | awk -F "=" '{gsub("2XSPEED-","",$1); print $1"-"$2}'); hashprint=$(echo $COURSE | md5sum | cut -c 1,2,3,4); echo "$titname($hashprint);[sound:./$COURSE/$each]" >> "$CSVNAME"; rsync -v "$each" "$ANKISTORAGE/$COURSE/$each"; done
		sort "$CSVNAME" > tempcsv 
		mv tempcsv "$CSVNAME"
		#ANKI ISN'T READY FOR THIS###awk 'BEGIN {for(i = 1; i <= 42; i++)printf "TESTFILE;"; printf "\n"}; {print $0}' tempcsv > $CSVNAME; echo -e "\n"; read -p "Generated file: $CSVNAME.  Press enter to review changes in editor."; $VISUAL "$CSVNAME" 
		clear; mediamenu
	 fi
          ;;
  esac
done


IFS=$SAVEIFS
}
clear
mediamenu
